M_str = {
    'M_0':  'm_0 * [TAG-plasma]',
    'M_1':  'f([INS],alpha_1,beta_1,gamma_1,delta_1) * [FFA^{loc}_{pl}]_{myo}',
    'M_2':  'm_2 * [FFA]_{myo}',
    'M_3':  'm_3 * [FA-CoA]_{myo}',
    'M_4':  'm_4 * [Ac-CoA]_{myo}',
    'M_5':  'm_5 * [FA-CoA]_{myo} * [Gly3P]_{myo}',
    'M_6':  'm_6 * [TAG]_{myo}',
    'M_7':  'f([INS],alpha_7,beta_7,gamma_7,delta_7) * [Gluc]_{myo}',
    'M_8':  'f([INS],alpha_8,beta_8,gamma_8,delta_8) * [G6P]_{myo}',
    'M_9':  'f([INS],alpha_9,beta_9,gamma_9,delta_9) * [G6P]_{myo}',
    'M_10': 'm_10 * [GG]_{myo]',
    'M_11': 'm_11 * [G3P]_{myo} * [[H]n-c]_{myo} * [ATP-c]_{myo}',
    'M_12': 'f([INS],α_12,β_12,γ_12,δ_12)*f([Ac-Coa]_{myo},α_12_2,β_12_2,γ_12_2,δ_12_2)*[Pyr]_{myo}',
    'M_13': 'm_13 * [KB-plasma]',
    'M_14': 'm_14 * [AA]_{myo}',
    'M_15': 'm_15 * [AA]_{myo}',
    'M_16': 'm_16 * [AA]_{myo}',
    'M_17': 'f([AA-food],alpha_17,beta_17,gamma_17,delta_17) * [muscle]_{myo}',
    'M_18': 'm_18 * [AA]_{myo}',
    'M_19': 'f([AA-food],alpha_19,beta_19,gamma_19,delta_19) * [AA]_{myo}',
    'M_20': 'm_20 * [AA-food]',
    'M_21': 'm_21 * [Pyr]_{myo} * [[H]n-c]_{myo}',
    'M_22': 'm_22 * [Lac]_{myo}',
    'M_23': 'f([INS],alpha_23,beta_23,gamma_23,delta_23)* [Gluc-plasma]',
    'M_24': 'm_24 * [Cytr]_{myo}',
    'M_25': 'm_25 * [[H]nf-m]_{myo}',
    'M_26': 'm_26 * [ATP-m]_{myo}',
    'M_27': 'm_27 * [G3P]_{myo} * [[H]n-c]_{myo}',
    'M_28': 'm_28 * [Gly3P]_{myo}',
    'M_29': 'm_29 * [[H]f-m]_{myo}',
    'M_30': 'm_30 * [ATP-c]_{myo}',
    'M_31': 'f([INS],alpha_31,beta_31,gamma_31,delta_31)*[LD]_{myo}'
}
des_str_ = {
    '[INS]':                    'alpha * J_carb + beta * J_fat + gamma * J_prot - CL * [INS]',
    '[Gluc-plasma]':            'J_carb - M_23',
    '[AA-food]':                'J_prot - M_20 + M_19',
    '[TAG-plasma]':             'J_fat - M_0',
    # блок 1
    '[FFA^{loc}_{pl}]_{myo}':   'M_0 - M_1 - SP_m',
    '[FFA]_{myo}':              'M_1 + 3 * M_31 - M_2',
    '[FA-CoA]_{myo}':           'M_2 - M_3 - M_5',
    '[TAG]_{myo}':              'M_5 - M_6',
    '[LD]_{myo}':               'M_6 - M_31',
    # блок 2
    '[Gly3P]_{myo}':            'M_27 - M_5 - M_28',
    '[G3P]_{myo}':              'M_28 + M_8 - M_27 - M_11',
    '[G6P]_{myo}':              'M_7 + M_10 - M_8 - M_9',
    '[Gluc]_{myo}':             'M_23 - M_7',
    '[GG]_{myo}':               'M_9 - M_10',
    '[Pyr]_{myo}':              'M_11 + M_15 - M_12 - M_21',
    '[Lac]_{myo}':              'M_21 - M_22',
    '[[H]n-c]_{myo}':           'M_11 - M_21 - M_27',
    '[ATP-c]_{myo}':            'M_11 - M_30',
    '[[H]f-m]_{myo}':           'M_28 - M_29',
    # блок 3
    '[Ac-CoA]_{myo}':           'M_12 + M_3 + M_14 + M_13 - M_4',
    '[Cytr]_{myo}':             'M_4 - M_24',
    '[OAA]_{myo}':              'M_16 + M_24 - M_4',
    '[CO_2]_{myo}':             'M_24 + M_12',
    '[[H]nf-m]_{myo}':          'M_24 + M_29 - M_25',
    '[ATP-m]_{myo}':            'M_25 - M_26 - M_30',
    # блок 4
    '[AA]_{myo}':               'M_20 + M_17 - M_14 - M_15 - M_16 - M_18 - M_19',
    '[muscle]_{myo}':           'M_18 - M_17'
}
